# Workflow name
name: S3 Objects Upload CI

# When to run: on pushes or pull requests to main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Global environment variables
env:
  BUCKET_NAME: "githubactions-pl"
  AWS_REGION: "us-east-1"

# Permissions needed for OIDC role assumption and repo access
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: actions_S3
          role-to-assume: arn:aws:iam::211125299414:role/GitHub_OIDC_Role

      # Step 3: Extract branch name
      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      # Step 4: Extract commit hash
      - name: Extract commit hash
        id: extract_hash
        run: echo "commit_hash=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      # Step 5: Zip the project files
      - name: Zip project files
        run: |
          mkdir -p artifacts
          zip -r ./artifacts/project.zip . -x "node_modules/**" ".git/**" "dist/**"

      # Step 6: Upload the zip file to S3 using AWS CLI
      - name: Upload to S3
        run: |
          aws s3 cp ./artifacts/project.zip s3://${{ env.BUCKET_NAME }}/${{ steps.extract_branch.outputs.branch }}/latest/project.zip
